name: Ayoratou

services:
  uptime:
    image: ayoratou99/uptime-ayoratou:latest
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
